base:

development:
  inherit: base
  contact_email: "rafael@rafaeldohms.com.br, listas@rafaeldohms.com.br"

  
production:
  inherit: development
  contact_email: "rafael@rafaeldohms.com.br, listas@rafaeldohms.com.br"