base:

development:
  inherit: base
  contact_email: "sys@rafaeldohms.com.br"

staging:
  inherit: development
  contact_email: "sys@rafaeldohms.com.br"
  
production:
  inherit: development
  contact_email: "contato@nerdtrack.com.br"